# -*- coding: utf-8 -*-
"""0502測試.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Od5ClmZwTpsSVyF3oRL3Z0OtlEAL2fIE
"""

#import gdown
import os
import glob
import re
import pandas as pd

# ==========================================
# 1. 下載公開的 Google Drive 資料夾
# ==========================================
# 請將下方的 URL 替換成你實際的 Google Drive 資料夾公開連結
folder_url = 'data'

# 定義輸出資料夾名稱
output_dir = 'data'


def download_drive_folder(folder_url, output_dir):
    # 檢查並創建輸出資料夾
    os.makedirs(output_dir, exist_ok=True)
    print(f"已創建或已存在輸出資料夾: {output_dir}")

    # 使用 gdown 下載整個資料夾的內容
    # gdown 的 Python API 會直接處理下載資料夾
    # try:
    #     gdown.download_folder(folder_url, output=output_dir, quiet=False, use_cookies=False)
    # except Exception as exc:
    #     raise RuntimeError(f"下載 Google Drive 資料夾失敗: {exc}")

    print(f"\n資料夾內容已下載至: {output_dir}")

# ==========================================
# 2. 定義切片與資料夾處理邏輯
# ==========================================
def process_all_txt_in_folder(directory_path, max_length=200):
    all_segments_data = []

    # 遞迴尋找資料夾內所有的 .txt 檔案
    txt_files = glob.glob(os.path.join(directory_path, "**/*.txt"), recursive=True)

    if not txt_files:
        print("警告：在指定的資料夾中找不到任何 .txt 檔案。")
        return pd.DataFrame()

    print(f"找到 {len(txt_files)} 個 txt 檔案，開始進行切片處理...")

    for file_path in txt_files:
        # 讀取單一文本
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        if not lines:
            continue

        # 擷取 Meta Data (假設第1行是標題，第2行是作者，其餘是內文)
        title = lines[0].strip() if len(lines) > 0 else "未知標題"
        author = lines[1].strip() if len(lines) > 1 else "未知作者"
        content = "".join(lines[2:])

        # 切片邏輯 (以換行符號切割成段落)
        paragraphs = [p.strip() for p in content.split('\n') if p.strip()]

        segments = []
        for p in paragraphs:
            # 若段落長度在限制內，直接算作一個片段
            if len(p) <= max_length:
                segments.append(p)
            else:
                # 若段落過長，按標點符號進行「軟切分」
                sentences = re.split(r'([。！？；])', p)
                current_segment = ""

                for i in range(0, len(sentences) - 1, 2):
                    sentence = sentences[i]
                    punctuation = sentences[i+1] if (i+1) < len(sentences) else ""
                    full_sentence = sentence + punctuation

                    if len(current_segment) + len(full_sentence) <= max_length:
                        current_segment += full_sentence
                    else:
                        if current_segment:
                            segments.append(current_segment)
                        current_segment = full_sentence

                if current_segment:
                    segments.append(current_segment)

        # 將該檔案切出來的所有片段，加入總清單中
        for i, seg in enumerate(segments):
            all_segments_data.append({
                "source_file": os.path.basename(file_path), # 紀錄來源檔名以便追蹤
                "title": title,
                "author": author,
                "segment_id": i + 1,
                "text_segment": seg,
                "length": len(seg)
            })

    # 將所有資料轉換為 DataFrame
    return pd.DataFrame(all_segments_data)


# ==========================================
# 3. 執行處理並匯出結果
# ==========================================
def main():
    download_drive_folder(folder_url, output_dir)

    # 執行批次處理 (設定 max_length=200)
    df_all_segments = process_all_txt_in_folder(output_dir, max_length=200)

    if df_all_segments.empty:
        print("\n未產生任何文本片段。請檢查是否有 .txt 檔案存在於下載的資料夾中。")
        return

    print(f"\n處理完成！共產出 {len(df_all_segments)} 個文本片段。")

    # 匯出成 CSV 檔案供後續 BERT 訓練使用
    csv_filename = "processed_segments.csv"
    df_all_segments.to_csv(csv_filename, index=False, encoding='utf-8-sig') # 使用 utf-8-sig 避免 Excel 開啟亂碼
    print(f"已將結果儲存為 {csv_filename}")

    # 顯示前 5 筆結果預覽
    print("\n前 5 筆結果預覽:")
    print(df_all_segments.head().to_string(index=False))


if __name__ == "__main__":
    main()